name: Daily Summaries

on:
    schedule:
        - cron: "0 8 * * *" # Runs at 6am PST every day
    workflow_dispatch: # Allows you to run it manually for testing

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Build the Docker image
              env:
                  HF_TOKEN: ${{secrets.HF_TOKEN}}
                  NEWS_API_TOKEN: ${{secrets.NEWS_API_TOKEN}}
                  SUPABASE_URL: ${{secrets.SUPABASE_URL}}
                  SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
              run: docker compose up daily
